version: 2.1
jobs:
  build: 
    docker:
      - image: circleci/python:3.7.3
      
    steps:
      - checkout
      - run:
          command: |
            sudo pip3 install matplotlib numpy scikit_image pylint
            pylint jigsolver
            python -m unittest discover ./ "*_test.py"
          name: Test

