version: 2.1
jobs:
  build: 
    docker:
      - image: circleci/python:3.7.3
      
    steps:
      - checkout
      - run:
          command: |
            sudo pip3 install matplotlib numpy scikit_image
            python -m unittest discover jigsaw-puzzle-solver "*_test.py"
          name: Test

